#! /usr/bin/env bash

set -euo pipefail

maas_dir=maas-docs
core_dir=ubuntu-core-docs
conjureup_dir=conjure-up-docs
builder_dir=documentation-builder
landscape_dir=landscape-docs
phone_dir=phone-docs

rm -rf ${core_dir} && git clone https://github.com/canonicalltd/ubuntu-core-docs.git ${core_dir} || true
rm -rf ${maas_dir} && git clone https://github.com/canonicalltd/maas-docs.git ${maas_dir} || true
rm -rf ${landscape_dir} && git clone https://github.com/canonicalltd/docs-landscape.git ${landscape_dir} || true
rm -rf ${conjureup_dir} && git clone https://github.com/canonicalltd/docs-conjure-up.git ${conjureup_dir} || true
rm -rf ${builder_dir} && git clone https://github.com/canonicalltd/documentation-builder.git ${builder_dir} || true
rm -rf ${phone_dir} && git clone https://github.com/ubuntudesign/phone-docs.git ${phone_dir} || true

# Extra build steps for Ubuntu Core docs
(
  cd ${core_dir}
  repo init -u https://github.com/canonicalltd/ubuntu-core-docs.git
  repo sync
)

documentation-builder --base-directory ${core_dir}  \
                      --site-root '/core/'  \
                      --output-path templates/core  \
                      --output-media-path static/media/core  \
                      --search-url '/search'  \
                      --search-placeholder 'Search Core docs'  \
                      --search-domain 'docs.ubuntu.com/core'  \
                      --media-url '/static/media/core'  \
                      --tag-manager-code 'GTM-K92JCQ'  \
                      --no-link-extensions \
                      --force

documentation-builder --base-directory ${maas_dir}  \
                      --site-root '/maas/'  \
                      --output-path templates/maas  \
                      --output-media-path static/media/maas  \
                      --search-url '/search'  \
                      --search-placeholder 'Search MAAS docs'  \
                      --search-domain 'docs.ubuntu.com/maas'  \
                      --media-url '/static/media/maas'  \
                      --tag-manager-code 'GTM-K92JCQ'  \
                      --no-link-extensions \
                      --build-version-branches \
                      --force

documentation-builder --base-directory ${landscape_dir}  \
                      --site-root '/landscape/'  \
                      --output-path templates/landscape  \
                      --output-media-path static/media/landscape  \
                      --search-url '/search'  \
                      --search-placeholder 'Search Landscape docs'  \
                      --search-domain 'docs.ubuntu.com/landscape'  \
                      --media-url '/static/media/landscape'  \
                      --tag-manager-code 'GTM-K92JCQ'  \
                      --no-link-extensions \
                      --force

documentation-builder --base-directory ${conjureup_dir}  \
                      --site-root '/conjure-up/'  \
                      --output-path templates/conjure-up  \
                      --output-media-path static/media/conjure-up  \
                      --search-url '/search'  \
                      --search-placeholder 'Search Conjure-up docs'  \
                      --search-domain 'docs.ubuntu.com/conjure-up'  \
                      --media-url '/static/media/conjure-up'  \
                      --tag-manager-code 'GTM-K92JCQ'  \
                      --no-link-extensions \
                      --force

documentation-builder --base-directory ${builder_dir}  \
                      --source-folder docs  \
                      --site-root '/documentation-builder/'  \
                      --output-path templates/documentation-builder  \
                      --output-media-path static/media/documentation-builder  \
                      --search-url '/search'  \
                      --search-placeholder 'Search Builder docs'  \
                      --search-domain 'docs.ubuntu.com/documentation-builder'  \
                      --media-url '/static/media/documentation-builder'  \
                      --no-link-extensions \
                      --force

documentation-builder --base-directory ${phone_dir}  \
                      --site-root '/phone/'  \
                      --output-path templates/phone  \
                      --output-media-path static/media/phone  \
                      --search-url '/search'  \
                      --search-placeholder 'Search Phone docs'  \
                      --search-domain 'docs.ubuntu.com/phone'  \
                      --media-url '/static/media/phone'  \
                      --tag-manager-code 'GTM-K92JCQ'  \
                      --no-link-extensions \
                      --force

