#! /usr/bin/env bash

maas_dir=maas-docs
core_dir=ubuntu-core-docs
snapcraft_dir=snapcraft-docs

git-force-clone https://github.com/CanonicalLtd/maas-docs.git ${maas_dir}
git-force-clone -b 1.0.0-structure https://github.com/nottrobin/ubuntu-core-docs.git ${core_dir}
#git clone https://github.com/canonicalltd/snapcraft-docs.git ${snapcraft_dir}

documentation-builder --base-directory ${maas_dir}  \
                      --site-root '/maas/'  \
                      --output-path templates/maas  \
                      --output-media-path static/media/maas  \
                      --media-url '/static/media/maas'  \
                      --no-link-extensions \
                      --force

documentation-builder --base-directory ${core_dir}  \
                      --site-root '/core/'  \
                      --output-path templates/core  \
                      --output-media-path static/media/core  \
                      --media-url '/static/media/core'  \
                      --no-link-extensions \
                      --force

#documentation-builder --base-directory ${snapcraft_dir}  \
#                      --site-root '/snapcraft/'  \
#                      --output-path templates/snapcraft  \
#                      --output-media-path static/media/snapcraft  \
#                      --media-url '/static/media/snapcraft'  \
#                      --no-link-extensions

