version: 2

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev:1.7.0
      environment:
        SECRET_KEY: local_development_fake_key

jobs:
  test-site:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn && pip3 install -r requirements.txt
      - run:
          name: Build the site resources
          command: yarn run build
      - run:
          name: Run the site server
          command: ./entrypoint 0.0.0.0:80
          background: true
      - run:
          name: Check site is accessible
          command: sleep 3 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://localhost
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint python code
          command: yarn lint-python
  lint-scss:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint sass
          command: yarn lint-scss
  test-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn && pip3 install -r requirements.txt
      - run:
          name: Yarn build
          command: yarn build
      - run:
          name: Install dependencies
          command: pip3 install coverage
      - run:
          name: Run tests with coverage
          command: |
            coverage run  --source=. -m unittest discover tests
            bash <(curl -s https://codecov.io/bash) -cF python
workflows:
  version: 2
  build:
    jobs:
      - test-site
      - lint-scss
      - lint-python
      - test-python
